### PR TITLE
added projects to coach serializer

### LINKED ISSUE #389: add projects to coach serializer
add a list of projects (to which the coach is assigned to) to the coach serializer

### PR DESCRIPTION
**Pull request by leveys**
closes #389

### CODE REVIEW

**Comment by leveys** [comment]
example response body:
```
{
    "url": "http://localhost:8000/api/coaches/1/",
    "id": 1,
    "first_name": "Peter",
    "last_name": "Parker",
    "email": "[coach@example.com](mailto:coach@example.com)",
    "is_admin": false,
    "is_active": false,
    "projects": [
        "http://localhost:8000/api/projects/7/"
    ]
}
```

**Review by Zelzahn — APPROVED** [review]

**Comment by lisadejonghe** [comment]
Is it possible to return the name of the project immediately? That's the only thing I need for the table and it would be nice if I should not get a full project to just display the name.

**Comment by leveys** [comment]
```
{
    "url": "http://localhost:8000/api/coaches/1/",
    "id": 1,
    "first_name": "Peter",
    "last_name": "Parker",
    "email": "[coach@example.com](mailto:coach@example.com)",
    "is_admin": false,
    "is_active": false,
    "projects": [
        {
            "id": 7,
            "url": "http://localhost:8000/api/projects/7/",
            "name": "Project K"
        }
    ]
}
```

like this?

**Comment by lisadejonghe** [comment]
yes perfect, thank you!

**Review by Wouter01 — APPROVED** [review]

**Pull request merged**
