### PR TITLE
added ordering

### LINKED ISSUE #328: add sorting to api endpoints

### PR DESCRIPTION
**Pull request by leveys**
added ordering query parameter to the backend
closes #328

### CODE REVIEW

**Comment by lisadejonghe** [comment]
Can I sort on all possible fields? Can I sort on both first and last name? Can I also sort descending and ascending?

**Comment by lisadejonghe** [comment]
Can I sort on all possible fields? Can I sort on both first and last name? Can I also sort descending and ascending?

**Comment by leveys** [comment]
on what fields should ordering be possible?
i dont think it's useful to sort on a link to a cv for example
both ascending and descending ordering is possible
@lisadejonghe

**Comment by lisadejonghe** [comment]
I would like to sort on email, full name (first and last name) and role for `users`.
I would like to sort on email, full name (first and last name) and status for `students`.
I would like to sort on skill name and comment for `skills`.

**Review by lisadejonghe — APPROVED** [review]

**Pull request merged**
