### PR TITLE
Websocket improvements

### LINKED ISSUE #335: centralise websocket baseURL's
Currently the baseURl's are spread over a couple of places. It would be better were this only handled in 1 place.

### PR DESCRIPTION
**Pull request by Zelzahn**
- Fixes #335 
- When assigning a student to a project and the other window has the "on project" check activated, the student is now added to the list

### CODE REVIEW

**Comment by Wouter01** [comment]
>     * When assigning a student to a project and the other window has the "on project" check activated, the student is now added to the list

Is this only valid for this filter, or also for the other filters?

**Comment by lisadejonghe** [comment]
I have that too, yes.

**Comment by Zelzahn** [comment]
I will look into this!

**Comment by Zelzahn** [comment]
Adding a user to a project will now correctly remove it from the sidebar if onProject is `maybe` or `no` and removing a user from a project will also correctly remove it if onProject is `true`.

**Review by Wouter01 — COMMENTED** [review]
https://user-images.githubusercontent.com/62355975/167151368-ac8fe036-467f-4bb9-b0a8-d312e10a91ce.mov

It's now partially working for me, but still not fully working.

**Comment by lisadejonghe** [comment]
It's the same for me @Wouter01

**Comment by Zelzahn** [comment]
Further progress of this PR is temporarily paused until #244 is fixed.

**Comment by Zelzahn** [comment]
@Wouter01 It should be fixed now

**Comment by Wouter01** [comment]
> @Wouter01 It should be fixed now

I still can't get it to work. @lisadejonghe , can you verify?

**Review by Wouter01 — APPROVED** [review]

**Pull request merged**
