### PR TITLE
Delete all

### LINKED ISSUE #448: Delete all data button
Add delete all data button to frontend.

### PR DESCRIPTION
**Pull request by lasaeren**
also contains changes to change password:
- move to own component since it didnt belong in toptoolbar
- now uses server feedback & displays it to user
- better rules, local checking before submitting to server
- fix the layout the toggle eyes were out of the input field

closes #448

### CODE REVIEW

**Comment by lasaeren** [comment]
TODO: clean up & fix build errors

**Comment by lasaeren** [comment]
there are some ts-ignores cuz otherwise I cant access the field and I have no idea how to fix it

**Comment by lisadejonghe** [comment]
- Could you change the color of the 'advanced options' to black?
- Maybe redirect projects or students when having deleted something using href (not router) so the storage will be deleted?
- Instead of showing an error when 'DELETE COACHES' is not typed in, you could disable the 'DELETE' button.
- Could you fix the Vue build errors?

**Comment by lasaeren** [comment]
@lisadejonghe 
> * Could you change the color of the 'advanced options' to black?
Do you mean when the tab is selected or the title of the page or ?
> * Maybe redirect projects or students when having deleted something using href (not router) so the storage will be deleted?
Maybe you want to delete more so I'd just stay on the page
> * Instead of showing an error when 'DELETE COACHES' is not typed in, you could disable the 'DELETE' button.
Tried it doesn't work
> * The 'change password' button is broken? It works on `main`.
You broke it when merging main into the branch, you forgot to import the `ChangePasswordDialog`
> * Could you fix the Vue build errors?
They were fixed not sure what went wrong

**Comment by lisadejonghe** [comment]
> @lisadejonghe
> 
> > * Could you change the color of the 'advanced options' to black?
> 
> Do you mean when the tab is selected or the title of the page or ?
> 
I mean the selected tab.

> > * Maybe redirect projects or students when having deleted something using href (not router) so the storage will be deleted?
> 
> Maybe you want to delete more so I'd just stay on the page
> 
Why would you want this, that's the reason for the checkboxes, no?

> > * Instead of showing an error when 'DELETE COACHES' is not typed in, you could disable the 'DELETE' button.
> 
> Tried it doesn't work
> 
There must be a way to make it work no?

> > * The 'change password' button is broken? It works on `main`.
> 
> You broke it when merging main into the branch, you forgot to import the `ChangePasswordDialog` [HERE](https://github.com/SELab-2/OSOC-5/pull/451/commits/b33bcb271a83d29e167b4703b06eadab871038a9#diff-91266d2767d4a80e361b9a31b44be948bfd303cfd43897bc4630038407a97ab0L153)
> 
Woops, my bad.

> > * Could you fix the Vue build errors?
> 
> They were fixed not sure what went wrong
>
Using `// @ts-ignore` is not really a solution if that's what you mean.

**Comment by Wouter01** [comment]
> > * Maybe redirect projects or students when having deleted something using href (not router) so the storage will be deleted?
> 
> 
> 
> Maybe you want to delete more so I'd just stay on the page
> 
> 
I also think it's better to route to /projects, I would suspect the user would check all the things it wants to delete, and he/she does not need to be on that page anymore. Also, is it possible to reset the stores after the data has been deleted?

> > * Instead of showing an error when 'DELETE COACHES' is not typed in, you could disable the 'DELETE' button.
> 
> 
> 
> Tried it doesn't work
> 
> 
I also think this is a cleaner, more intuitive way of doing this. I have done something similar in CreateProject.vue, maybe you could have a look at it?

**Comment by lasaeren** [comment]
@lisadejonghe
> > > * Could you change the color of the 'advanced options' to black?
> > 
> > 
> > Do you mean when the tab is selected or the title of the page or ?
> 
> I mean the selected tab.
> 

this is the same as the toptoolbar the selected part is highlighted

> > > * Maybe redirect projects or students when having deleted something using href (not router) so the storage will be deleted?
> > 
> > 
> > Maybe you want to delete more so I'd just stay on the page
> 
> Why would you want this, that's the reason for the checkboxes, no?
> 

I would just stay on the page to make it clear that it worked & so u can delete other things as well if you want to do one by one. But if you really want a redirect then so be it.


> > > * Instead of showing an error when 'DELETE COACHES' is not typed in, you could disable the 'DELETE' button.
> > 
> > 
> > Tried it doesn't work
> 
> There must be a way to make it work no?
> 

Yeah if you check after every typed character if the button can be turned on, but it's kinda overkill and useless since pressing it wont do anything anyways.



> > > * The 'change password' button is broken? It works on `main`.
> > 
> > 
> > You broke it when merging main into the branch, you forgot to import the `ChangePasswordDialog` [HERE](https://github.com/SELab-2/OSOC-5/pull/451/commits/b33bcb271a83d29e167b4703b06eadab871038a9#diff-91266d2767d4a80e361b9a31b44be948bfd303cfd43897bc4630038407a97ab0L153)
> 
> Woops, my bad.
> 
No problem

> > > * Could you fix the Vue build errors?
> > 
> > 
> > They were fixed not sure what went wrong
> 
> Using `// @ts-ignore` is not really a solution if that's what you mean.

If you scroll up a bit I said I tried to fix it but I couldn't but the build errors now are different ones and showed up when u merged main into this branch.

**Comment by lisadejonghe** [comment]
The redirect is indeed not that good since the download buttons are also on that page.

**Comment by Wouter01** [comment]
> > > > * Instead of showing an error when 'DELETE COACHES' is not typed in, you could disable the 'DELETE' button.
> > > 
> > > 
> > > Tried it doesn't work
> > 
> > 
> > There must be a way to make it work no?
> 
> Yeah if you check after every typed character if the button can be turned on, but it's kinda overkill and useless since pressing it wont do anything anyways.
> 
No, you do something like :disabled="var === 'DELETE STUDENTS'". Have you had a look at my example code?

> > > > * Could you fix the Vue build errors?
> > > 
> > > 
> > > They were fixed not sure what went wrong
> > 
> > 
> > Using `// @ts-ignore` is not really a solution if that's what you mean.
> 
> If you scroll up a bit I said I tried to fix it but I couldn't but the build errors now are different ones and showed up when u merged main into this branch.

This is because you did not use `defineComponent` in the new Vue file. If you add that, you'll be able to fix your ts issues.

**Comment by Wouter01** [comment]
Disabled is fixed.

**Comment by lasaeren** [comment]
> > > > > * Instead of showing an error when 'DELETE COACHES' is not typed in, you could disable the 'DELETE' button.
> > > > 
> > > > 
> > > > Tried it doesn't work
> > > 
> > > 
> > > There must be a way to make it work no?
> > 
> > 
> > Yeah if you check after every typed character if the button can be turned on, but it's kinda overkill and useless since pressing it wont do anything anyways.
> 
> No, you do something like :disabled="var === 'DELETE STUDENTS'". Have you had a look at my example code?
> 

if only it was that simple, you don't know the amount of variables, the only way to do this is by calling a function every time any of the fields is changed and then setting the variable in the :disabled but I felt like this is overkill for a feature that's only used 1 time but feel free to add it

> > > > > * Could you fix the Vue build errors?
> > > > 
> > > > 
> > > > They were fixed not sure what went wrong
> > > 
> > > 
> > > Using `// @ts-ignore` is not really a solution if that's what you mean.
> > 
> > 
> > If you scroll up a bit I said I tried to fix it but I couldn't but the build errors now are different ones and showed up when u merged main into this branch.
> 
> This is because you did not use `defineComponent` in the new Vue file. If you add that, you'll be able to fix your ts issues.

oh I'll look into that

**Comment by lasaeren** [comment]
fixed build issues, delete all is finished

**Review by Zelzahn — APPROVED** [review]

**Pull request merged**
