### PR TITLE
changed some fields on_delete to SET_NULL

### LINKED ISSUE #317: keep some data when removing students/coaches/skills
what happens in the current version:
- delete skill:
  - not possible if used in projectsuggestion
  - removed in student skill list
  - removed in project required skill list
- delete student
  - projectsuggestions removed
  - sentemail removed
- delete project:
  - all information removed (requiredskills, projectsuggestions)
- delete coach:
  - suggestions removed 
  - removed in project coaches list
  - projectsuggestions removed 
  - sentemail removed 

i think some of these interactions should be changed, some data should be kept when an object is deleted
see https://github.com/SELab-2/OSOC-opgave/discussions/51

### PR DESCRIPTION
**Pull request by leveys**
closes #317

### CODE REVIEW

**Comment by leveys** [comment]
a couple fields are now set to null when the object they referenced is deleted, namely:
- coach field of Suggestion
- student and coach fields of ProjectSuggestion
- sender and receiver fields of SentEmail

this should be better than just cascade deleting (for example: deleting a suggestion when the coach that made it is deleted)

i think it woul be nice if in the frontend it said something like 'this user/student was deleted' instead of 'null'

**Review by Zelzahn — APPROVED** [review]
Looks good to me, we mustn't forget then to create a new front-end issue for the null replacement.

**Comment by leveys** [comment]
i agree, maybe we wait to merge this until there is a pr ready for the frontend side of this?

**Comment by leveys** [comment]
okay, i will change this pr to draft to make sure it doesn't accidentally get merged

**Comment by Zelzahn** [comment]
Oops I see that my earlier comment wasn't so clear, but what I meant was that we could merge this into a branch like `updated-delete` and then use that branch as the branch for the FE updates.

**Review by Zelzahn — APPROVED** [review]

**Pull request merged**
