### PR TITLE
Tally integration.

### PR DESCRIPTION
**Pull request by henricattoire**
- [x] Validate and transform tally forms.
- [x] Add custom endpoint for tally to post to.
- [x] Update fixtures to add skills from tally.
- [x] #194.
- [x] Add developer documentation for tally integration.

See #44.

Can the reviewers also read the [new wiki entry](https://github.com/SELab-2/OSOC-5/wiki/Developer-documentation) and give feedback?

### CODE REVIEW

**Review by leveys — APPROVED** [review]
shouldn't the `tally.py` and `test.json` files be in the `tally` subfolder?

**Comment by henricattoire** [comment]
I must have accidentally added `test.json`, it is of no use. Yes, moving `tally.py` to the tally subfolder seems reasonable. I will look at it tomorrow so I can merge this pr.

**Comment by henricattoire** [comment]
Every action fails because they also fail on main. I tested my changes locally and they work.

**Comment by leveys** [comment]
can you try to remake the migrations? i see that the migrations in this branch are incorrect

**Comment by henricattoire** [comment]
Yes, because they are also incorrect on main. Am I allowed to fix it with this pr?

**Comment by leveys** [comment]
i think its ok to fix them here, when #254 is done, it will have to merge with main anyway.

**Review by leveys — APPROVED** [review]

**Comment by henricattoire** [comment]
[Now](https://github.com/SELab-2/OSOC-5/runs/6156785732?check_suite_focus=true) `test_delete_skill_not_found` and `test_delete_skill` seem to fail (`403`) . Is this normal? The others tests error because of the redis but I just added support for that (normally).

**Comment by leveys** [comment]
this is because the DELETE skill api endpoint has changed, now only admins can delete a skill and only if it is not used in a project.
these tests are fixed in be/tests. maybe its better to merge this branch first?

**Pull request merged**
