### PR TITLE
Fe/decision student

### PR DESCRIPTION
**Pull request by lisadejonghe**
This pull request has:

- dialog to input a reason for final decision

### CODE REVIEW

**Comment by lisadejonghe** [comment]
@Zelzahn There's still a little bug where the suggestion pops up, then disappears and pops up again when doing a suggestion/decision.

**Comment by Zelzahn** [comment]
> @Zelzahn There's still a little bug when making a decision for the first time. The loading pops up, then disappears and pops up again.

This'll probably be because we first receive the data from the websocket and only then the `loadStudent()` call is finished. I'll look into this.

**Comment by Zelzahn** [comment]
@lisadejonghe Does the issue still persist?

**Comment by lisadejonghe** [comment]
The issue is there for a suggestion, but I quess this is not a big problem. I will merge with main and then this pull request can be merged in main.

**Review by Zelzahn — APPROVED** [review]

**Pull request merged**
