### PR TITLE
Backend pagination.

### LINKED ISSUE #300: Backend pagination
The backend currently has no pagination. This should be possible for student, projects, users, skills at least.

### PR DESCRIPTION
**Pull request by henricattoire**
Implement pagination in the backend (both for normal get requests and filtered ones). Because our application uses non-generic views, 

```python
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}
```
in the settings file cannot be used. Instead, a custom pagination class needs to be defined. It is still possible to use the settings variable using a [workaround](https://stackoverflow.com/questions/45670648/how-to-use-pagination-in-a-non-generic-view-viewset) but adding a single pagination class is much cleaner and leaves room for customisation in the future. The workaround also requires the setting to be put in both `dev` and `prod` (simply putting it in `common` does not work) which is not ideal. 

Closes #300.

### CODE REVIEW

**Comment by henricattoire** [comment]
@lisadejonghe Where do you need pagination? I already added it to students.

**Comment by lisadejonghe** [comment]
See #300 : student, projects, users, skills. Is it also possible to get a custom number of entries? In the frontend, this can be selected.

**Comment by henricattoire** [comment]
> Is it also possible to get a custom number of entries? In the frontend, this can be selected.

Yes, just add `?page_size=N` as a query parameter in your requests (where N is the number of items per page). For example,

```
http://localhost:8000/api/students/?page_size=2
```

will have 2 results per page.

**Review by lisadejonghe — APPROVED** [review]

**Comment by lisadejonghe** [comment]
That's certainly big enough!

**Review by leveys — CHANGES_REQUESTED** [review]
right now, there are a couple tests that fail because of the pagination, i will look into this

also, i would add some documention about the query parameter, as right now it's not very clear that it can be used

**Review by henricattoire — COMMENTED** [review]
I will add documentation.

**Review by henricattoire — COMMENTED** [review]
Tests seem to work now. Thanks!

**Review by leveys — APPROVED** [review]

**Pull request merged**
