### PR TITLE
add final decision to suggestions

### PR DESCRIPTION
**Pull request by lisadejonghe**
This pull request adds the final decision to the suggestions card. It also fixed the reloading of the sidebar when deleting a student.

image

@Zelzahn I get an `undefined undefined` when doing a decision. Any idea why I get this?

### CODE REVIEW

**Comment by Zelzahn** [comment]
Found the reason
image

**Review by Zelzahn — COMMENTED** [review]
I'm wondering if the current way of showing the final decision could be misinterpreted? Maybe it would be more clear if we were to add a label?

**Comment by lisadejonghe** [comment]
What kind of label? Where?

**Comment by Zelzahn** [comment]
Maybe a label underneath "Suggestions" with the text "Final decision" in Subtitle typography?

**Comment by lisadejonghe** [comment]
Like this? I deleted the line in this case.

image

**Comment by Zelzahn** [comment]
I would keep the line, but for the rest this looks perfect!

**Comment by lisadejonghe** [comment]
This way?

image

**Review by Zelzahn — APPROVED** [review]
Yes, thank you!

**Pull request merged**
