### PR TITLE
Fe/filter coaches

### PR DESCRIPTION
**Pull request by lisadejonghe**
This pull request has:

- backend call to filter userlist

### CODE REVIEW

**Comment by lisadejonghe** [comment]
@Wouter01 I think that the useTableFilter can be deleted? This will fix the Vue Cl error.

**Comment by Wouter01** [comment]
> @Wouter01 I think that the useTableFilter can be deleted? This will fix the Vue Cl error.

I think that's correct.

**Comment by Wouter01** [comment]
I noticed a weird filter result, but I think this is related to the backend filter? @leveys 
afbeelding

**Review by Wouter01 — APPROVED** [review]

**Comment by leveys** [comment]
could you show the full email object (coach, info)?
i have tested it in the backend with an email to this student and it doesn't show up when i search 'app'

**Comment by lisadejonghe** [comment]
This is added in #326

**Pull request closed without merging**
